src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import(
    
    signup_view,
    logout_view,
    home_view,
    login_view
    
)


app_name='accounts'
urlpatterns = [
    path('signup/',signup_view,name='signup'),
    path('logout/',logout_view,name='logout'),
    path('home/',home_view, name='homes'),
    path('login/',login_view,name='login'),

       # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

src/chat/urls.py
from django.urls import path
from chat.views import(
    home,
    room,
    send,
    getMessages,
    checkview
)

app_name='chat'
urlpatterns = [
    path('',home, name='home'),
    path('<str:room>/',room, name='room'),
    path('checkview',checkview, name='checkview'),
    path('send',send, name='send'),
    path('getMessages/<str:room>/',getMessages, name='getMessages'),

]

src/dashboards/urls.py
from django.urls import path

from dashboards.views import(
    home_dashboard_view,
    payment_dashboard_view,
    settings_dashboard_view,
    edit_profile_view,
    mpesa_payment_dashboard_view,
    lipa_na_mpesa,
    receipt_dash_view
)


app_name='dashboards'

urlpatterns = [
    
    path('dmain/',home_dashboard_view,name='homedash'),
    path('payment/',payment_dashboard_view,name='payment'),
    path('mpayment/',mpesa_payment_dashboard_view,name='mpayment'),
    path('settings/',settings_dashboard_view,name='settings'),
    path('editprofile/',edit_profile_view,name='editprofile'),
    path('receipt/',receipt_dash_view,name='receipt'),
    # path('lipa_na_mpesa',lipa_na_mpesa,name='payed'),
    # path('pay/',lipa,name='payed'),


    

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from officials.views import default_home_view,default_apartment_view,default_about_view, default_contact_view
# from accounts.views import home_view
# from accounts.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('dashboards/',include('dashboards.urls')),
    path('chats/',include('chat.urls')),
    path('',default_home_view,name='home'),
    
    path('apartment/',default_apartment_view,name='apartmentpic'),
    path('about/',default_about_view,name='about'),
    path('contact/',default_contact_view,name='contact'),

    # path('logout/',logout_view,name='logout')
    # path('dmain/',home_dashboard_view,name='homedash')

    path('api-auth/', include('rest_framework.urls')),

    path('api/v1/', include('mpesa_api.urls')),
    # path('api/payment/', include('mpesa_api.api.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
        
</head>
<body>
    {%block content%}
    {%endblock %}
    
</body>
</html>

src/templates/base2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rental</title>
    <!-- <link rel="stylesheet" href="styles.css"> -->

    {% if request.user.is_authenticated %}
	  	<!-- <a class="p-2 text-dark" href="">Home</a>
	    <a class="p-2 text-dark" href="">Account</a> -->
	    <p>Hello {{request.user.username}}||<a class="p-2 text-dark" href="{%url 'accounts:logout'%}">Logout</a></p>
    {%else%}
        <p><a href="{%url 'accounts:signup'%}">Register</a> ||<a href="{%url 'accounts:login'%}"></a></p>
	{% endif %}	
</head>

<body>
    <header>
        <a href="{%url 'home'%}"><img class="deflogo" src="{%url 'home'%}" alt="Logo"></a>
        
        <nav>
            <ul class="nav_links">
                <!-- <li><a href="#">Services</a></li> -->
                <li><a href="{% url 'contact'%}">Contacts</a></li>
                <li><a href="{% url 'about'%}">About</a></li>
                <li><a href="{% url 'apartmentpic'%}">Apartment</a></li>

            </ul>
        </nav>
        <a class="login"  href="{% url 'accounts:signup'%}"><button>Sign up</button></a>
        <a class="login"  href="{% url 'accounts:login'%}"><button>Login</button></a>
    </header>
    {%block content%}

    {%endblock%}

</body>
</html>


<style type="text/css">
    *
{
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    background-color: #242524;
}

li,a ,button{
    font-family: sans-serif;
    font-weight: 500;
    font-size: 15px;
    color: #edf0f1;
    text-decoration: none;


}
header{
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 30px 10%;
}
.logo{
    cursor:pointer;
}
.nav_links{
    list-style: none;
}
.nav_links li{
    display: inline-block;
    padding: 0px 20px;
}
button{
    padding: 9px 25px;
    background-color: rgba(0,136, 169,1);
    border: none;
    border-radius: 40px;
    cursor: pointer;
    transition: all 0.3s ease-in-out 0s;
}
.nav_links li a {
    transition: all 0.3s ease-in-out 0s;
}
.nav_links li a:hover{
    color:  #99ffeb ;
}
button:hover{
    background-color: rgba(0,136,169,0.5);
}
</style>

src/templates/base3.html
<!DOCTYPE html>
<!-- Created By CodingNepal -->
<html lang="en" dir="ltr">
   <head>
      <meta charset="utf-8">
      <title>Animated Sidebar Menu | CodingLab</title>
      <link rel="stylesheet" href="style.css">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"/>
   </head>
   <body>
      <div class="wrapper">
         <input type="checkbox" id="btn" hidden>
         <label for="btn" class="menu-btn">
         <i class="fas fa-bars"></i>
         <i class="fas fa-times"></i>
         </label>
         <nav id="sidebar">
            <div class="title">
               Side Menu
            </div>
            <ul class="list-items">
               <li><a href="{% url 'dashboards:homedash'%}"><i class="fas fa-home"></i>Home</a></li>
               <li><a href="{% url 'dashboards:payment'%}"><i class="fas fa-money-check"></i>Paypal</a></li>
               <li><a href="{% url 'dashboards:mpayment'%}"><i class="fas fa-money-check"></i>Mpesa</a></li>
               <li><a href="{% url 'dashboards:settings'%}"><i class="fas fa-cog"></i>Settings</a></li>
               <li><a href="{%url 'dashboards:editprofile'%}"><i class="fas fa-user"></i>Profile</a></li>
               <li><a href="{%url 'dashboards:receipt'%}"><i class="fas fa-globe-asia"></i>Receipts</a></li>
               <li><a href="{%url 'chat:home'%}"><i class="fas fa-envelope"></i>Messages</a></li>
               <li><a href="{%url 'accounts:logout'%}"><i class="fas fa-power-off "></i>Log Out</a></li>
               <div class="icons">
                  <a href="#"><i class="fab fa-facebook-f"></i></a>
                  <a href="#"><i class="fab fa-twitter"></i></a>
                  <a href="#"><i class="fab fa-github"></i></a>
                  <a href="#"><i class="fab fa-youtube"></i></a>
               </div>
            </ul>
         </nav>
      </div>
      {%block content%}

      {%endblock%}
   </body>
</html>

<style type="text/css">
    @import url('https://fonts.googleapis.com/css?family=Poppins:400,500,600,700&display=swap');
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
    }
    .wrapper{
    height: 100%;
    width: 300px;
    position: relative;
    }
    .wrapper .menu-btn{
    position: absolute;
    left: 20px;
    top: 10px;
    background: #4a4a4a;
    color: #fff;
    height: 45px;
    width: 45px;
    z-index: 9999;
    border: 1px solid #333;
    border-radius: 5px;
    cursor: pointer;
    display: flex;
    align-items: center;
    justify-content: center;
    transition: all 0.3s ease;
    }
    #btn:checked ~ .menu-btn{
    left: 247px;
    }
    .wrapper .menu-btn i{
    position: absolute;
    transform: none;
    font-size: 23px;
    transition: all 0.3s ease;
    }
    .wrapper .menu-btn i.fa-times{
    opacity: 0;
    }
    #btn:checked ~ .menu-btn i.fa-times{
    opacity: 1;
    transform: rotate(-180deg);
    }
    #btn:checked ~ .menu-btn i.fa-bars{
    opacity: 0;
    transform: rotate(180deg);
    }
    #sidebar{
    position: fixed;
    background: #404040;
    height: 100%;
    width: 270px;
    overflow: hidden;
    left: -270px;
    transition: all 0.3s ease;
    }
    #btn:checked ~ #sidebar{
    left: 0;
    }
    #sidebar .title{
    line-height: 65px;
    text-align: center;
    background: #333;
    font-size: 25px;
    font-weight: 600;
    color: #f2f2f2;
    border-bottom: 1px solid #222;
    }
    #sidebar .list-items{
    position: relative;
    background: #404040;
    width: 100%;
    height: 100%;
    list-style: none;
    }
    #sidebar .list-items li{
    padding-left: 40px;
    line-height: 50px;
    border-top: 1px solid rgba(255,255,255,0.1);
    border-bottom: 1px solid #333;
    transition: all 0.3s ease;
    }
    #sidebar .list-items li:hover{
    border-top: 1px solid transparent;
    border-bottom: 1px solid transparent;
    box-shadow: 0 0px 10px 3px #222;
    }
    #sidebar .list-items li:first-child{
    border-top: none;
    }
    #sidebar .list-items li a{
    color: #f2f2f2;
    text-decoration: none;
    font-size: 18px;
    font-weight: 500;
    height: 100%;
    width: 100%;
    display: block;
    }
    #sidebar .list-items li a i{
    margin-right: 20px;
    }
    #sidebar .list-items .icons{
    width: 100%;
    height: 40px;
    text-align: center;
    position: absolute;
    bottom: 100px;
    line-height: 40px;
    display: flex;
    align-items: center;
    justify-content: center;
    }
    #sidebar .list-items .icons a{
    height: 100%;
    width: 40px;
    display: block;
    margin: 0 5px;
    font-size: 18px;
    color: #f2f2f2;
    background: #4a4a4a;
    border-radius: 5px;
    border: 1px solid #383838;
    transition: all 0.3s ease;
    }
    #sidebar .list-items .icons a:hover{
    background: #404040;
    }
    .list-items .icons a:first-child{
    margin-left: 0px;
    }
    .content{
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%,-50%);
    color: #202020;
    z-index: -1;
    width: 100%;
    text-align: center;
    }
    .content .header{
    font-size: 45px;
    font-weight: 700;
    }
    .content p{
    font-size: 40px;
    font-weight: 700;
    }

</style>