src/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts.views import(
    
    signup_view,
    logout_view,
    home_view,
    login_view
    
)


app_name='accounts'
urlpatterns = [
    path('signup/',signup_view,name='signup'),
    path('logout/',logout_view,name='logout'),
    path('home/',home_view, name='homes'),
    path('login/',login_view,name='login'),

       # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),

    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),

    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),

    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),
]

src/chat/urls.py
from django.urls import path
from chat.views import(
    home,
    room,
    send,
    getMessages,
    checkview
)

app_name='chat'
urlpatterns = [
    path('',home, name='home'),
    path('<str:room>/',room, name='room'),
    path('checkview',checkview, name='checkview'),
    path('send',send, name='send'),
    path('getMessages/<str:room>/',getMessages, name='getMessages'),

]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from officials.views import default_home_view,default_apartment_view,default_about_view, default_contact_view
# from accounts.views import home_view
# from accounts.views import logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('dashboards/',include('dashboards.urls')),
    path('chats/',include('chat.urls')),
    path('',default_home_view,name='home'),
    
    path('apartment/',default_apartment_view,name='apartmentpic'),
    path('about/',default_about_view,name='about'),
    path('contact/',default_contact_view,name='contact'),

    # path('logout/',logout_view,name='logout')
    # path('dmain/',home_dashboard_view,name='homedash')

    path('api-auth/', include('rest_framework.urls')),

    path('api/v1/', include('mpesa_api.urls')),
    # path('api/payment/', include('mpesa_api.api.urls')),
    
]

urlpatterns += staticfiles_urlpatterns()

src/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.
class MyAccountManager(BaseUserManager):
	def create_user(self, email, username, password=None):
		if not email:
			raise ValueError('Users must have an email address')
		if not username:
			raise ValueError('Users must have a username')

		user = self.model(
			email=self.normalize_email(email),
			username=username,
		)

		user.set_password(password)
		user.save(using=self._db)
		return user

	def create_superuser(self, email, username, password):
		user = self.create_user(
			email=self.normalize_email(email),
			password=password,
			username=username,
		)
		user.is_admin = True
		user.is_staff = True
		user.is_superuser = True
		user.save(using=self._db)
		return user

class Account(AbstractBaseUser):
	

	email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
	username 				= models.CharField(max_length=30, unique=True)
	phone 					= models.CharField(max_length=10,null=True,blank=True)
	room_numb 				= models.CharField(max_length=4,null=True,blank=True)
	date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
	last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
	is_admin				= models.BooleanField(default=False)
	is_active				= models.BooleanField(default=True)
	is_staff				= models.BooleanField(default=False)
	is_superuser			= models.BooleanField(default=False)


	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = ['username']

	objects = MyAccountManager()

	def __str__(self):
		return self.email

	# For checking permissions. to keep it simple all admin have ALL permissons
	def has_perm(self, perm, obj=None):
		return self.is_admin

	# Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
	def has_module_perms(self, app_label):
		return True

src/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from accounts.models import Account


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Account
        fields = ('email', 'username', 'password1', 'password2','phone','room_numb' )


class AccountAuthenticationForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Account
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

src/accounts/views.py
from django.shortcuts import render,redirect
# from django.contrib.auth.forms import UserCreationForm
from accounts.forms import RegistrationForm, AccountAuthenticationForm
from django.contrib.auth import login, authenticate, logout
# Create your views here.

def signup_view(request):
    # context={}
    # form = UserCreationForm()
    # context['form'] = form
    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            raw_password = form.cleaned_data.get('password1')
            account = authenticate(email=email, password=raw_password)
            login(request, account)
            return render(request,'accounts/login.html')
        else:
            context['registration_form'] = form

    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'accounts/signup.html', context)



def logout_view(request):
	logout(request)
	return redirect('home')


def login_view(request):

	context = {}

	user = request.user
	if user.is_authenticated: 
		return redirect("dashboards:homedash")

	if request.POST:
		form = AccountAuthenticationForm(request.POST)
		if form.is_valid():
			email = request.POST['email']
			password = request.POST['password']
			user = authenticate(email=email, password=password)

			if user:
				login(request, user)
				return redirect("dashboards:homedash")

	else:
		form = AccountAuthenticationForm()

	context['login_form'] = form

	# print(form)
	return render(request, "accounts/login.html", context)

def home_view(request):
    context={}
    return render(request,'accounts/index.html',context)

src/accounts/templates/accounts/index.html
{%extends 'base.html'%}

{%block content%}

    <h1>home page</h1>
    {%if request.user.si_authenticated%}
        <p>Hello , {{request.user.username}}  // <a href="{%url 'logout'%}">Logout</a></p>
    {% else %}

    {%endif%}


{%endblock%}

src/accounts/templates/accounts/login.html
{% extends 'base2.html' %}


{% block content %}

<style type="text/css">
  .form-signin {
    width: 100%;
    max-width: 330px;
    padding: 15px;
    margin: auto;
    background-color: antiquewhite;
    }

  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    background-color: antiquewhite;
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    background-color: antiquewhite;
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
  .h3  {
    background-color: antiquewhite;
    text-align: center;
  }
  a{
    /* margin-top: 10px; */
    text-align: center;
    border-radius: 5px;
  }
  button{
    margin-bottom: 5px;
  }
</style>


<form class="form-signin" method="post">{% csrf_token %}
  <div class="d-flex flex-column pb-3">
    
  </div>
  
  <h1 class="h3 mb-3 font-weight-normal">Login</h1>

  <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  
  <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>

  {% for field in login_form %}
      <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  {% if login_form.non_field_errors %}
    <div style="color: red">
      <p>{{login_form.non_field_errors}}</p>
    </div>
      
  {% endif %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Log in</button>
  <div class="d-flex flex-column">
    <a class`="m-auto" href="{% url 'accounts:password_reset' %}">Reset password</a>
  </div> 
</form>





{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends 'base2.html'%}


{%block content%}







<style type="text/css">
  .form-signin {
  width: 100%;
  max-width: 330px;
  padding: 20px;
  margin: auto;
  background-color: antiquewhite;
  margin-top: 70px;
  }
  .form-signin .form-control {
    position: relative;
    box-sizing: border-box;
    height: auto;
    padding: 10px;
    font-size: 16px;
  }
  .form-signin .form-control:focus {
    z-index: 2;
  }
  .form-signin input[type="email"] {
    margin-top: 5px;
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="text"] {
    margin-bottom: 15px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: 4px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  .h3{
    text-align: center;
  }
  .form-signin input{
    background-color: antiquewhite;
    padding-top: 5px;
  }
  .form-signin button{
    margin-top: 10px;
  }
  h1{
    background-color: antiquewhite;
  }

</style>


<form class="form-signin" method="post">{% csrf_token %}
  <!-- <div class="d-flex flex-column pb-3">
    <img class="img-fluid mx-auto d-block" src="" alt="LOGO" width="72" height="72">
  </div> -->
  <h1 class="h3 mb-3 font-weight-normal">Register an account</h1>

  <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

  <input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>
  
  <input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>

  <input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>

  <input type="number" name="phone" id="inputPhone" class="form-control" placeholder="Phone Number"
    required>

  <input type="number" name="room_number" id="inputroom_number" class="form-control" placeholder="Room Number"
    required>

  {% for field in registration_form %}
      <p>
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
  {% endfor %}
  {% if registration_form.non_field_errors %}
    <div style="color: red">
      <p>{{registration_form.non_field_errors}}</p>
    </div>
      
  {% endif %}

  <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

  </form>


{% endblock %}
  